name: star-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - python-dateutil==2.8.2
  - sage=10.3
  - ripser=0.6.14
  - numpy=1.26.2
  - pandas=2.2.2
  - matplotlib==3.8.1
  - scipy==1.11.3
  - gudhi==3.12.0
  - persim==0.3.8
  - scikit-learn==1.3.2
  - seaborn==0.12.2
  - jupyterlab==4.2.1
  - tqdm==4.66.1
  - joblib
  - pip
  - pip:
      - pytest
      - jupyter
      - notebook
      - nbconvert
      - nbformat
      
