name: star-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - sage=10.7
  - numpy
  - pandas
  - matplotlib
  - joblib
  - ripser
  - pip
  - pip:
      - pytest
      - jupyter
      - notebook
      - nbconvert
      - nbformat
